# Generated by Django 2.1.1 on 2018-09-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojemność', models.IntegerField(blank=True, null=True)),
                ('ilość_cylindrów', models.IntegerField(blank=True, null=True)),
                ('rodzaj', models.CharField(choices=[('parowy', 'Parowy'), ('inny', 'Inny'), ('odrzutowy', 'Odrzutiwy'), ('benz', 'Benz'), ('disel', 'Disel')], max_length=50)),
            ],
        ),
    ]
